server:
  port: 5858
  servlet:
    context-path: /auth

spring:
  thread-executor: virtual
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_server
    username: authorization_server
    password: authorization_server
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        generate_statistics: true
        session.events.log: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  # End Gateway Configuration

logging:
  level:
    root: ERROR
    com:
      deft: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        cache: DEBUG
        stat: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
