
spring:
  cloud:
    gateway:
      global-filter:
        - AuthenticationFilter
        - LoggingGlobalFilter
      routes:
        - id: reward
          uri: http://localhost:8081
          predicates:
            - Path=/reward/**
        - id: notification
          uri: http://localhost:8082
          predicates:
            - Path=/notification/**
        - id: auth
          uri: http://localhost:5858
          predicates:
            - Path=/auth/**
          filters:
#            - RedirectionFilter
            - name: BeforeRedirectionFilter
              args:
                name: BeforeRedirectionFilter
                value: someValue
#            - name: ErrorHandlingFilter
#              args:
#                name: ErrorHandlingFilter
#                value: someValue
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
