# All traces should be sent to latency analysis tool
management:
  tracing.sampling.probability: 1.0
  endpoints.web.exposure.include: health,info,prometheus
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  # traceID and spanId are predefined MDC keys - we want the logs to include them
  logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
